blank_issues_enabled: false
contact_links:
  - name: Core issue submit
    url: https://github.com/uNetworking/uWebSockets.js/issues
    about: Link to issues of framework which nanoexpress built on top
  - name: Help
    url: https://stackoverflow.com/questions/tagged/nanoexpress
    about: Any help or issues like cannot run example should be posted here
  - name: Updates channel
    url: https://t.me/nanoexpress
    about: Updates channel
  - name: Discussion
    url: https://t.me/nanoexpress_discussion
    about: Discussion chat
  - name: Dedicated support
    url: https://t.me/dalisoft
    about: Dedicated premium support from author
